name: Git Flow

on:
  pull_request_target:
    branches:
      - main
      - dev

jobs:
  ensure-base-branch-is-dev:
    if: ${{ github.base_ref == 'main' }}
    name: "Ensure base branch is 'dev'"
    runs-on: ubuntu-20.04
    env:
      COMMENT_BODY: |
        Thank you for your contribution!
        New PRs should use `dev` as the base branch.

        The base branch will be automatically changed for you.

    steps:
      - name: Submit a PR comment
        uses: actions/github-script@v5
        with:
          script: |
            const { COMMENT_BODY } = process.env

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${COMMENT_BODY}`
            })

      - name: "Change the base branch to 'dev'"
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              base: 'dev',
            })
